### ISSUE TITLE
There was a bug in tdlib that crashed my whole program

### ISSUE THREAD

**Issue by HuMzan** [tdlight-team/tdlight-java#69] opened 2022-01-09 05:37 UTC
TDLib fatal error: [ 0][t36][1641700688.451681137][Td.h:140][#3634][!MessagesManager][&close_flag_ < 1]  1 td::ActorId<ActorType> td::Td::create_net_actor(ArgsT&& ...) [with ActorT = td::SendMessageActor; ArgsT = {}]

This is the only information I get useful

**Comment by HuMzan** [comment] 2022-01-09 05:41
My guess might be that the client exit and send message concurrently happened

**Comment by HuMzan** [comment] 2022-01-09 05:42
Can avoid the entire program crashing due to a client error?

**Comment by cavallium** [comment] 2022-01-09 11:39
This is a fatal error, not a normal error. You are doing something terribly wrong. Perhaps are you using tdlib after it has been closed?

**Comment by cavallium** [comment] 2022-01-09 11:39
Meanwhile I'm closing this issue because it's not a tdlight-java choice to crash the program, but a tdlib one.

**Closed by cavallium** 2022-01-09 11:39 UTC

**Comment by HuMzan** [comment] 2022-01-09 15:21
ok, i have feedback to Tdlib

**Comment by HuMzan** [comment] 2022-01-13 03:08
> Meanwhile I'm closing this issue because it's not a tdlight-java choice to crash the program, but a tdlib one.

![屏幕截图 2022-01-13 110619](https://user-images.githubusercontent.com/24567958/149258758-8744c388-558c-48b6-a1a4-583a90af5f0f.png)

I'm not quite sure about this, do you know anything?

**Comment by cavallium** [comment] 2022-01-13 10:02
Yes you are using tdlight, it is slightly modified, but this error is not caused by any modification of mine.
