### ISSUE TITLE
gcs shows no chats after jvm restart

### ISSUE THREAD

**Issue by MaaxGr** [tdlight-team/tdlight-java#27] opened 2021-02-08 22:47 UTC
I started the sample application, logged in via my telephone number and executed gcs. Everything works as expected. I get a list of my chats. I also can send messages or get details to a specific chat via gc command.

But after i restart my java app, i get into the following behaviour: I am still logged in. The "me" command returns my user including name and telephone number. But unfortunately the "gcs" command doesn't give me a response any more. Also "gc" doesn't work for the same chat-id that worked in the session in which i logged in.

This is the output of "gcs"
```
Enter command (gcs - GetChats, gc <chatId> - GetChat, me - GetMe, sm <chatId> <message> - SendMessage, lo - LogOut, q - Quit): 
gcs

First 20 chat(s) out of 0 known chat(s):
```

This is the output of "gc"
```
Error {
  code = 6
  message = "Invalid chat identifier specified"
}
```

Anything i did wrong or can do to fix this?

**Comment by Cavallium** [comment] 2021-02-10 10:01
That's strange, I don't know if it's a bug or something else.
Have you tried to reproduce this behavior in a different environment or user?

**Comment by MaaxGr** [comment] 2021-02-10 10:33
Unfortunately i only have one Telegram User. But i can try it out in a Linux Environment. I will come back to you

**Comment by Cavallium** [comment] 2021-02-10 10:33
Thanks

**Comment by MaaxGr** [comment] 2021-02-12 17:18
The problem is also present on arch linux.

That seems to be the problematic code lines:
```
                client!!.send(
                    GetChats(ChatListMain(), offsetOrder, offsetChatId, limit - mainChatList.size)
                ) { `object` ->
                    when (`object`.constructor) {
                        Error.CONSTRUCTOR -> System.err.println("Receive an error for GetChats:$newLine$`object`")
                        Chats.CONSTRUCTOR -> {
                            val chatIds = (`object` as Chats).chatIds
                            ....
```

It always goes into the Chats.CONSTRUCTOR case, but after jvm restart chatIds is a empty list.
Don't worry about the code syntax. I converted the example into kotlin lang.

Super weired problem

**Comment by MaaxGr** [comment] 2021-02-12 17:45
I created two new commands:
```
    "xx" -> client!!.send(GetContacts(), defaultHandler)
    "xxx" -> client!!.send(GetChats(ChatListArchive(), Long.MAX_VALUE, 10, 20), defaultHandler)
```

xx returns over 50 User-Objects
```
Users {
  totalCount = 59
  userIds = Array[59] {
    1234,
    5678, ....
```

xxx returns an empty list:
```
Chats {
  totalCount = 0
  chatIds = Array[0] {
  }
}
```

**Comment by MaaxGr** [comment] 2021-02-13 12:00
Okay, i disabled the following properties and now everything seems to work. But still not 100% clear, why this happens
```
TdApi.TdlibParameters parameters = new TdApi.TdlibParameters();
parameters.useMessageDatabase = false;
parameters.enableStorageOptimizer = false;
```

Issue can be closed from my side, if you don't want to investigate deeper into problem

**Comment by Cavallium** [comment] 2021-02-14 10:22
This two settings are unrelated to chats

**Comment by Cavallium** [comment] 2021-02-14 10:23
ChatListArchive returns empty because you are asking tdlib to get only the archived chats

**Comment by MaaxGr** [comment] 2021-02-15 17:56
oh yeah. That was just a copy paste error. Just played around with some other commands and configurations. Of course i mean this
```
 "xxx" -> client!!.send(GetChats(ChatListMain(), Long.MAX_VALUE, 10, 20), defaultHandler)
```


But nevertheless this parameter makes the difference for me:
```
parameters.useMessageDatabase = false
```

If the boolean is false i always get all chats
If the boolean is set to true, i only get the chats until i restart the app

**Comment by Cavallium** [comment] 2021-02-17 16:26
Thanks, I'll look into this problem. Probably it's not related to tdlight java but to tdlight.
Try to use TDLight Java with official TDLib, instead the one with tdlight.
https://github.com/tdlight-team/tdlight-java#for-tdlight-java-with-official-tdlib

**Comment by Cavallium** [comment] 2021-03-16 20:07
It should be fixed with the current release.

**Closed by Cavallium** 2021-03-16 20:07 UTC
